# Setup
title:        My Blog
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       hanjh
  url:        https://hanjinhang.github.io/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

# Siderbar settings
sidebar: true
sidebar-about-description: "。。。。。。"
#sidebar-avatar:/img/avatar-by.JPG
